[package]
name = "solitario"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
cards_core = { path = "../cards_core" }
thiserror = "1.0.63"
anyhow = { version = "1.0.86", features = ["backtrace"] }
